### ISSUE TITLE
FileNotFoundError: [Errno 2] "dot" not found in path.

### ISSUE THREAD

**Issue by kobayashi90** [linuxgemini/ripe-lg-graph#3]
Not sure if i did something wrong!  

```
python3 ripe-lg-graph.py 2606:4700:4700::/48
Contacting RIPE NCC RIS looking glass...
Processing all available RRCs...
Now processing: RRC00 - Amsterdam, Netherlands
/root/ripe-lg-graph/ripe-lg-graph.py:155: DeprecationWarning: please use dns.resolver.resolve() instead
  data = dns.resolver.query(f"AS{asn}.asn.cymru.com", "TXT").response.answer[0][0].to_text().replace("'","").replace('"','')
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pydot.py", line 1912, in create
    stdout_data, stderr_data, process = call_graphviz(
  File "/usr/lib/python3.9/site-packages/pydot.py", line 129, in call_graphviz
    process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ripe-lg-graph/ripe-lg-graph.py", line 307, in <module>
    make_bgpmap(rrc, rrc_data_dict)
  File "/root/ripe-lg-graph/ripe-lg-graph.py", line 273, in make_bgpmap
    graph.write(f"./output/{target_folder}/png/{rrc_full}.png", format="png")
  File "/usr/lib/python3.9/site-packages/pydot.py", line 1817, in write
    s = self.create(prog, format, encoding=encoding)
  File "/usr/lib/python3.9/site-packages/pydot.py", line 1922, in create
    raise OSError(*args)
FileNotFoundError: [Errno 2] "dot" not found in path.

```

**Comment by linuxgemini** [comment]
From README: `*(external dependency: dot)*`

You need GraphViz to be installed, this is a **required** external dependency.
